title: Prashik Patil
url: "https://prashikiitb.me"
baseurl: "https://prashikpatil221.github.io/portfolio"
author: Prashik 
# description: "Prashik Patil's portfolio webpage"
markdown: kramdown
ins_logo: "iitb.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/prashikpatil221"
footer_text: "With love"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/index"
 - name: "Resume"
   link: "/PrashikPatil_Resume.pdf"
 - name: "Contact"
   link: "/contact"
 - name: "Blog"
   link: "/blog"

theme: jekyll-theme-minimal