title: Prashik Patil
url: "https://prashikiitb.me"
baseurl: "."
author: Prashik 
# description: "Prashik Patil's portfolio webpage"
markdown: kramdown
ins_logo: "iitb.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/prashikpatil221"
footer_text: "With love"

sass:
    style: compressed
    sass_dir: _sass

nav:
hello world!
#  - name: "About"
#    link: "/index"
#  - name: "Resume"
#    link: "/PrashikPatil_Resume .pdf"
#  - name: "Contact"
#    link: "/contact.md"
#  - name: "Blog"
#    link: [Twitter](https://x.com/hotshott_22)

theme: jekyll-theme-minimal
